### ISSUE TITLE
LVGL Library

### ISSUE THREAD

**Issue by Seahorde** [Seeed-Studio/Seeed_Arduino_RoundDisplay#4]
When building against the latest LVGL 9.0 on Platform.IO in VS Studio CodeI have lots of build errors.

In order to build the demo project, the older 8.xx LVGL library needs to be used.

**Comment by Seahorde** [comment]
Building against LVGL 8.3.9,8.3.8

I see errors: 
```
region RAM overflowed with stack, region `RAM' overflowed by 27284 bytes
collect2: error: ld returned 1 exit status
```

**Comment by skitzo2000** [comment]
I experienced similar issues on a fresh install of the Arduino IDE and LVGL library, switching back to an 8.3.x version fixed the problem for me as well.

**Comment by Maxwelltoo** [comment]
Already supports both LVGL 8.x and 9.x
