### ISSUE TITLE
Micropython support

### ISSUE THREAD

**Issue by slabua** [Seeed-Studio/Seeed_Arduino_RoundDisplay#7]
Would it be possible to have official micropython support? Specifically, to use it with the RP version of the boards?

**Comment by baorepo** [comment]
https://github.com/russhughes/gc9a01_mpy @Cincinnatu  Please port out product to this repo

**Comment by slabua** [comment]
I have checked this different version that seems to be working as well
https://github.com/russhughes/gc9a01py

**Comment by baorepo** [comment]
could you help us test it? @slabua

**Comment by slabua** [comment]
@baorepo yes i will check it later tonight. I think I may have also found something for the touch panel, I'll check that too.

**Comment by slabua** [comment]
I've got the display working with:
https://github.com/russhughes/gc9a01py

```
spi = SPI(0, baudrate=60000000, sck=Pin(2), mosi=Pin(3))
tft = gc9a01.GC9A01(
    spi,
    dc=Pin(29, Pin.OUT),
    cs=Pin(27, Pin.OUT),
    reset=Pin(26, Pin.OUT),
    backlight=Pin(0, Pin.OUT),
    rotation=0)
```
![GbnTj7GbwAAPCpS](https://github.com/user-attachments/assets/1be5b656-47ef-40ae-9599-e139bd7593a9)

And the touch working with:
https://github.com/bdbarnett/mpdisplay/blob/main/drivers/touch/chsc6x.py

```
i2c = I2C(1, sda=Pin(6), scl=Pin(7), freq=400000)
touch = CHSC6X(i2c, irq_pin=1)
```
![GbnVH8-bAAAYeID](https://github.com/user-attachments/assets/aa1b5106-85f8-4718-a252-386e2c799c74)

**Comment by baorepo** [comment]
@slabua  Great. You did it. 
@limengdu  @Chunchun-tian  I recommend that you put this content on your product wiki to let more people know.
